name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'Build/**'
      - '.vs/**'
      - '.vscode/**'
      - '**/*.md'
      - '*.git*'

jobs:
  win32:
    name: Win32
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build project
        run: python .\Scripts\bet.py --build vs2022 
      
      - name: Run msbuild
        run: msbuild sad.sln -interactive:False -property:Configuration=Debug

      - name: Run tests
        run: python .\Scripts\bet.py --tests
  
  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build project
        run: python ./Scripts/bet.py --build gmake2

      - name: Compile project and run tests
        run: python ./Scripts/bet.py --compile-tests make
